require:
    - rubocop-rails
AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'db/migrate/*'
    - 'tmp/**/*'
    - 'spec/spec_helper.rb'
Layout/LineLength:
  Max: 100
Layout/BlockAlignment:
  Enabled: false
Rails/FilePath:
  Enabled: false
Style/AsciiComments:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/AbcSize:
  Max: 30
Metrics/BlockLength:
  Max: 55
Metrics/MethodLength:
  Max: 20
